plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
}

group 'org.zlab'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation 'com.github.javaparser:javaparser-core:3.25.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.12.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('dinv-monitor-shadow')
    archiveClassifier.set('')
    archiveVersion.set('')
    mergeServiceFiles()
}

task getModifiedFields(type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('org.zlab.dinv.extractvars.ModifiedFields')
}
