import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
    id "com.diffplug.spotless" version "6.6.1"
}

group 'org.zlab'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation 'com.github.javaparser:javaparser-core:3.25.2'
    implementation 'com.github.javaparser:javaparser-symbol-solver-core:3.23.0' // replace with the current version
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.12.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'
    implementation 'info.picocli:picocli:4.6.1'
    implementation 'org.jgrapht:jgrapht-core:1.5.1' // Use the latest version
    implementation 'org.apache.commons:commons-lang3:3.12.0'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('dinv-monitor-shadow')
    archiveClassifier.set('')
    archiveVersion.set('')
    mergeServiceFiles()

//    dependencies {
//        exclude(dependency('com.github.javaparser:javaparser-core:3.25.2'))
//        exclude(dependency('com.github.javaparser:javaparser-symbol-solver-core:3.23.0'))
//    }

    include 'org/zlab/dinv/runtimechecker/Runtime*'
    include 'org/zlab/dinv/runtimechecker/Quant*'
}

// Defining a custom shadowJar task
task loggerShadowJar(type: ShadowJar) {
    archiveBaseName.set('logger-shadow')
    archiveClassifier.set('')
    archiveVersion.set('')

    from sourceSets.main.output // Adjust if using a different source set

    configurations = [project.configurations.runtimeClasspath]
}

application {
    mainClassName = 'org.zlab.dinv.visibility.Main'
}

test {
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed", "standardOut", "standardError"
    }
}

spotless {
    java {
        target("src/**/*.java") // apply formatting to all .java files under 'src' directory
//        googleJavaFormat() // for example, use the Google Java format
        eclipse().configFile '.settings/eclipse-java-google-style.xml'
    }
}
